name: CI/CD

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key
          chmod 600 private_key
          eval "$(ssh-agent -s)"
          ssh-add private_key

      - name: Deploy to EC2
        run: |
          HOSTNAME="${{ secrets.EC2_HOST }}"
          USER_NAME="${{ secrets.EC2_USERNAME }}"
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /var/www/html/testing_repo
            git fetch --tags
            latest_tag=$(git describe --tags --abbrev=0)
            git checkout $latest_tag
          '
